ايــــــــــوب خالد الزاحم
3700203

<h1> 1.1. Arrays </h1>

In [2]:
import numpy as np


In [7]:
# Exersise 1.1: Write a function that defines the following matrices as NumPy 
# arrays. 𝐴 = [[3 1 −1], [5 4 −9 ]] 𝐵 = [[ 2 −1 3 4], [7 2 −5 6], [9 3 −7 −2 ]]
# Return the matrix product AB. 
# Hint: use help() function to see how np.dot() function can be used!

def ex1():
    A = np.array([[3, -1, 4],
                  [1, 5, -9]])
    B = np.array([[2, 4, -5, 6],
                  [-1, 7, 9, 3],
                  [3, 2, -7, -2]])
    return np.dot(A, B)

ex1()

array([[ 19,  13, -52,   7],
       [-30,  21, 103,  39]])

In [9]:
help(np.ndarray)

Help on class ndarray in module numpy:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |

In [51]:
# Exersise 1.2: Explore how np.ndarray() can be used! Give an example?
arr = np.ndarray(shape = (2,3), dtype='int64')
arr = arr + 10
print(arr)

[[20 20 20]
 [20 20 20]]


<h1> 1.2. Basic Array Operations </h1>

In [18]:
# Exercise 1.3: Assume X, Y matrices are given as follows:
#𝑋 = [3 −4 1] 𝑌 = [5 2 3]
#what is the result of X+10? Y*4? X+Y? and X*Y? Write code down!

x = np.array([3, -4, 1])
y = np.array([5, 2, 3])

print(x + 10) # add 10 to all the values in the array
print(y * 4) # multipling by 4 to all the values in the array
print(x + y) # aggregate the x and y arrays values
print(x * y) # multipling the x and y arrays values

[13  6 11]
[20  8 12]
[ 8 -2  4]
[15 -8  3]


<h1> 1.4. Array Attributes </h1>

In [4]:
'''
    dtype: The type of the elements in the array.
    ndim:  The number of axes (dimensions) of the array.
    shape: A tuple of integers indicating the size in each dimension.
    size:  The total number of elements in the array.
'''
# Exercise 1.4: What is the output of A.ndim, A.shape, A.size?
# if A = np.array([[1, 2, 3],[4, 5, 6]]) 

a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a.dtype)
print(a.ndim)
print(a.shape)
print(a.size)
print(a[1,2])

int32
2
(2, 3)
6
6


In [21]:
# Exercise 1.5: Given A = np.array([[1, 2, 3],[4, 5, 6]]) 
# what is the current data type of A?______ 
# Change A type to float64  

a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a.dtype)

a = a.astype('float64')
print(a.dtype)

int32
float64


<h1> 1.5. Data Access  </h1>

<h2> 1.5.1  Array Slicing  </h2>

In [24]:
'''
    Indexing for a 1-D NumPy array uses the slicing syntax x[start:stop:step].
    If there is no colon, a single entry of that dimension is accessed.
    With a colon, a range of values is accessed. For multidimensional arrays,
    use a comma to separate slicing syntax for each axis.
    What does x = np.arange(10) do?____________________________  
'''
# Exercise 1.6: Using the code above, what is the output of
# x[3]?__________ 
# x[ : 4]_________ 
# x[4 :]_________   
# x[4:8]_________ 

x = np.arange(10)
print(x)

print(x[3]) # slicing index 3
print(x[:4]) # slicing from index 0 to 4
print(x[4:]) # slicing from index 4 to the last index
print(x[4:8]) # slicing from index 4 to 8 

[0 1 2 3 4 5 6 7 8 9]
3
[0 1 2 3]
[4 5 6 7 8 9]
[4 5 6 7]


In [25]:
# Exercise 1.7: Now, let x= np.array([[0,1,2,3,4],[5,6,7,8,9]]),
# what is the output of x[1, 2]?______  x[ : , 2 : ]? ________

x= np.array([[0,1,2,3,4],
             [5,6,7,8,9]])
print(x[1, 2]) # the element in the row index 1 and column index 2
print(x[:,2:]) # the elements after column index 2 in all the rows

7
[[2 3 4]
 [7 8 9]]


<h2> 1.5.2 Fancy Indexing  </h2>

In [28]:
'''
    So-called fancy indexing is a second way to access or change
    the elements of an array. Instead of using slicing syntax, 
    provide either an array of indices or an array of boolean values
    (called a mask) to extract specific elements. 
'''

x = np.arange(0, 50, 10)
print(x)
index = np.array([3, 1, 4])
print(x[index])

# A boolean array extracts the elements of 'x' at the same places as 'True'
mask = np.array([True, False, False, True, False])
print(x[mask])

[ 0 10 20 30 40]
[30 10 40]
[ 0 30]


In [31]:
'''
    Fancy indexing is especially useful for extracting or changing the 
    values of an array that meet some sort of criterion. 
    Use comparison operators like < and == to create masks. 
'''

# Fancy indexing with condition
y = np.arange(10, 20, 2) 
print(y)
mask = y > 15
print(mask)
print(y[mask])

# change the values that larger than 15 to 100
y[mask] = 100
print(y)

[10 12 14 16 18]
[False False False  True  True]
[16 18]
[ 10  12  14 100 100]


<h1> 1.6. Numerical Computing with NumPy </h1>

<h2> 1.6.1 Universal Functions </h2>

<table>
    <tr> 
        <th> Function </th>
        <th> Description </th>
    </tr>
    <tr> 
        <td> abs() or absolute() </td>
        <td> Calculate the absolute value element-wise. </td>
    </tr>
    <tr> 
        <td> exp() / log() </td>
        <td>  Exponential (ex) / natural log element-wise. </td>
    </tr>
    <tr> 
        <td> maximum() / minimum() </td>
        <td> Element-wise maximum / minimum of two arrays. </td>
    </tr>
    <tr> 
        <td> sqrt() </td>
        <td> The positive square-root, element-wise. </td>
    </tr>
    <tr> 
        <td> sin(), cos(), tan(), etc.</td>
        <td> Element-wise trigonometric operations </td>
    </tr>
</table>

<h2> 1.6.2 Other Array Methods  </h2>

<table>
    <tr> 
        <th> Method  </th>
        <th> Return </th>
    </tr>
    <tr> 
        <td> all() </td>
        <td> True if all elements evaluate to True. </td>
    </tr>
    <tr> 
        <td> any() </td>
        <td>  True if any elements evaluate to True. </td>
    </tr>
    <tr> 
        <td> argmax() </td>
        <td> Index of the maximum value. </td>
    </tr>
    <tr> 
        <td> argmin()  </td>
        <td> Index of the minimum value. </td>
    </tr>
    <tr> 
        <td> argsort()</td>
        <td> Indices that would sort the array. </td>
    </tr>
    <tr> 
        <td> clip()</td>
        <td> restrict values in an array to fit within a given range. </td>
    </tr>
    <tr> 
        <td> max()</td>
        <td> The maximum element of the array. </td>
    </tr>
    <tr> 
        <td> mean()</td>
        <td> The average value of the array. </td>
    </tr>
    <tr> 
        <td> min()</td>
        <td> The minimum element of the array. </td>
    </tr>
    <tr> 
        <td> sort()</td>
        <td> Return nothing; sort the array in-place. </td>
    </tr>
    <tr> 
        <td> std()</td>
        <td> The standard deviation of the array. </td>
    </tr>
    <tr> 
        <td> sum()</td>
        <td> The sum of the elements of the array. </td>
    </tr>
    <tr> 
        <td> var()</td>
        <td> The variance of the array. </td>
    </tr>
</table>

<h1> 2. Working on Iris.csv file</h1>

In [34]:
# import some data
from sklearn import datasets
iris = datasets.load_iris()
print(iris.filename)

C:\Users\ayyub\Anaconda3\lib\site-packages\sklearn\datasets\data\iris.csv


In [41]:
import numpy as np
data = np.genfromtxt('C:\\Users\\ayyub\\Anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\iris.csv',
                     delimiter=",", skip_header=1)

print(data)

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.2 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.6 1.4 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [5.  3.5 1

In [46]:
print('mean of {} is {}'.format(iris.feature_names[0], data[:,0].mean()))

mean of sepal length (cm) is 5.843333333333334


In [47]:
# Exercise 2: Do the same thing for other attributes including the following 
# methods (mean(), std(), var(), max(), and min())? Comment your observation!

print('mean of {} is {}'.format(iris.feature_names[0], data[:,0].mean()))
print('std of {} is {}'.format(iris.feature_names[0], data[:,0].std()))
print('var of {} is {}'.format(iris.feature_names[0], data[:,0].var()))
print('max of {} is {}'.format(iris.feature_names[0], data[:,0].max()))
print('min of {} is {}'.format(iris.feature_names[0], data[:,0].min()))

mean of sepal length (cm) is 5.843333333333334
std of sepal length (cm) is 0.8253012917851409
var of sepal length (cm) is 0.6811222222222223
max of sepal length (cm) is 7.9
min of sepal length (cm) is 4.3


In [52]:
# for the secound column
print('mean of {} is {}'.format(iris.feature_names[0], data[:,1].mean()))
print('std of {} is {}'.format(iris.feature_names[0], data[:,1].std()))
print('var of {} is {}'.format(iris.feature_names[0], data[:,1].var()))
print('max of {} is {}'.format(iris.feature_names[0], data[:,1].max()))
print('min of {} is {}'.format(iris.feature_names[0], data[:,1].min()))

mean of sepal length (cm) is 3.0573333333333337
std of sepal length (cm) is 0.4344109677354946
var of sepal length (cm) is 0.1887128888888889
max of sepal length (cm) is 4.4
min of sepal length (cm) is 2.0


In [53]:
# for the third column
print('mean of {} is {}'.format(iris.feature_names[0], data[:,2].mean()))
print('std of {} is {}'.format(iris.feature_names[0], data[:,2].std()))
print('var of {} is {}'.format(iris.feature_names[0], data[:,2].var()))
print('max of {} is {}'.format(iris.feature_names[0], data[:,2].max()))
print('min of {} is {}'.format(iris.feature_names[0], data[:,2].min()))

mean of sepal length (cm) is 3.7580000000000005
std of sepal length (cm) is 1.759404065775303
var of sepal length (cm) is 3.0955026666666665
max of sepal length (cm) is 6.9
min of sepal length (cm) is 1.0


In [54]:
# for the fourth column
print('mean of {} is {}'.format(iris.feature_names[0], data[:,3].mean()))
print('std of {} is {}'.format(iris.feature_names[0], data[:,3].std()))
print('var of {} is {}'.format(iris.feature_names[0], data[:,3].var()))
print('max of {} is {}'.format(iris.feature_names[0], data[:,3].max()))
print('min of {} is {}'.format(iris.feature_names[0], data[:,3].min()))

mean of sepal length (cm) is 1.1993333333333336
std of sepal length (cm) is 0.7596926279021594
var of sepal length (cm) is 0.5771328888888888
max of sepal length (cm) is 2.5
min of sepal length (cm) is 0.1


In [57]:
# for the fifth column
print('mean of {} is {}'.format(iris.feature_names[0], data[:,4].mean()))
print('std of {} is {}'.format(iris.feature_names[0], data[:,4].std()))
print('var of {} is {}'.format(iris.feature_names[0], data[:,4].var()))
print('max of {} is {}'.format(iris.feature_names[0], data[:,4].max()))
print('min of {} is {}'.format(iris.feature_names[0], data[:,4].min()))

mean of sepal length (cm) is 1.0
std of sepal length (cm) is 0.816496580927726
var of sepal length (cm) is 0.6666666666666666
max of sepal length (cm) is 2.0
min of sepal length (cm) is 0.0


In [62]:
import pandas as pd
df = pd.read_csv('C:\\Users\\ayyub\\Anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\iris.csv')
df.describe()

150           4      setosa  versicolor   virginica
count  150.000000  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.057333    3.758000    1.199333    1.000000
std      0.828066    0.435866    1.765298    0.762238    0.819232
min      4.300000    2.000000    1.000000    0.100000    0.000000
25%      5.100000    2.800000    1.600000    0.300000    0.000000
50%      5.800000    3.000000    4.350000    1.300000    1.000000
75%      6.400000    3.300000    5.100000    1.800000    2.000000
max      7.900000    4.400000    6.900000    2.500000    2.000000